SELECT
    RK.RACK_NO AS RACK_NO,
    RK.ITEM_CD AS ITEM_CD,
    IT.ITEM_NAME AS ITEM_NAME,
    RK.ITEM_NUMBER AS ITEM_NUMBER,
    RK.PRICE AS PRICE
FROM RACK RK
LEFT JOIN ITEM IT ON RK.ITEM_CD = IT.ITEM_CD
ORDER BY RK.RACK_NO